version: '3.8'
services:
  volatility-predictor:
    build: ..
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
      - ../models:/app/models
      - ../logs:/app/logs
      - ../mlruns:/app/mlruns
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
volumes:
  redis_data:
