data:
  root_dir: data
  symbols:
    indices: ["^NSEI", "^CNXIT", "^NSEBANK", "^CNXPHARMA"]
    equities_top10: ["RELIANCE.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS", "TCS.NS", "ITC.NS", "LT.NS", "SBIN.NS", "BHARTIARTL.NS", "HINDUNILVR.NS"]
  start_date: 2018-01-01
  end_date: null  # defaults to today
  cache_minutes: 60
  alt_sources:
    yahoo: true
    alpha_vantage: false
  fii_dii:
    enabled: true
  options:
    enabled: true

features:
  realized_vol_windows: [5, 10, 20, 60]
  lag_days: [1, 2, 3, 5]
  regime:
    hmm_states: 4
    gmm_components: 4

serving:
  host: 0.0.0.0
  port: 8000
  api_key_required: false
  rate_limit_per_minute: 120
  redis:
    host: ${REDIS_HOST:-localhost}
    port: 6379
    db: 0
    ttl_seconds: 900

backtest:
  initial_capital: 1000000
  transaction_cost_bps: 5
  walk_forward_window_days: 250
  forecast_horizons: [1, 5, 10, 20]

mlflow:
  experiment: volatility_india
  tracking_uri: null  # set env MLFLOW_TRACKING_URI to override

logging:
  level: INFO
  file: logs/app.log
  rotation_mb: 20
  retention: 10
